# Uncomment this line to define a global platform for your project
platform :ios, '9.0'

target 'SwiftCook' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SwiftCook
    pod 'FMDB'


  target 'SwiftCookTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SwiftCookUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
